export const en = {
  general: {
    title: 'Savage Worlds Character Sheet',
    save: 'Save Character',
    load: 'Load Character',
    language: 'Language',
    newCharacter: 'New Character',
    newCharacterConfirm: 'Are you sure you want to create a new character? All current character data will be lost.',
    cancel: 'Cancel',
    page: 'Page',
    saveToDb: 'Save to Database',
    loadFromDb: 'Load from Database',
  },
  characterInfo: {
    title: 'Character Information',
    name: 'Character Name',
    race: 'Race',
    rank: 'Rank',
    experience: 'Experience Points',
  },
  attributes: {
    title: 'Attributes',
    Agility: 'Agility',
    Smarts: 'Smarts',
    Spirit: 'Spirit',
    Strength: 'Strength',
    Vigor: 'Vigor',
    modifier: 'Modifier',
  },
  skills: {
    title: 'Skills',
    addSkill: 'Add Skill',
    skillName: 'Skill Name',
    importSkills: 'Import Skills',
    skillSet: 'Skill Set',
    dieType: 'Die Type',
    modifier: 'Modifier',
    linkedAttribute: 'Linked Attribute',
    defaultSkills: 'Default Skills',
    actions: 'Actions',
    sourcePage: 'Page'
  },
  derivedStats: {
    title: 'Derived Statistics',
    pace: 'Pace',
    parry: 'Parry',
    toughness: 'Toughness',
    charisma: 'Charisma',
  },
  combat: {
    title: 'Combat Statistics',
    wounds: 'Wounds',
    fatigue: 'Fatigue',
    bennies: 'Bennies',
  },
  edges: {
    title: 'Edges',
    addEdge: 'Add Edge',
    edgeName: 'Edge Name',
    description: 'Description',
    addExisting: 'Add Existing',
    selectEdge: 'Select Edge'
  },
  hindrances: {
    title: 'Hindrances',
    addHindrance: 'Add Hindrance',
    hindranceName: 'Hindrance Name',
    type: 'Type',
    description: 'Description',
    major: 'Major',
    minor: 'Minor',
    addExisting: 'Add Existing',
    selectHindrance: 'Select Hindrance'
  },
  gear: {
    title: 'Gear',
    addGear: 'Add Gear',
    itemName: 'Item Name',
    weight: 'Weight',
    notes: 'Notes',
    actions: 'Actions'
  },
  weapons: {
    title: 'Weapons',
    addWeapon: 'Add Weapon',
    weaponName: 'Weapon Name',
    range: 'Range',
    damage: 'Damage',
    ap: 'AP',
    weight: 'Weight',
    notes: 'Notes',
    addExisting: 'Add Existing',
    selectWeapon: 'Select Weapon',
    actions: 'Actions',
    sourcePage: 'Page'
  },
  powers: {
    title: 'Powers',
    addPower: 'Add Power',
    powerName: 'Power Name',
    powerPoints: 'Power Points',
    range: 'Range',
    duration: 'Duration',
    effect: 'Effect',
    addExisting: 'Add Existing',
    selectPower: 'Select Power',
    sourcePage: 'Page'
  },
}; 