export const ru = {
  general: {
    title: 'Лист Персонажа Savage Worlds',
    save: 'Сохранить Персонажа',
    load: 'Загрузить Персонажа',
    language: 'Язык',
    newCharacter: 'Новый Персонаж',
    newCharacterConfirm: 'Вы уверены, что хотите создать нового персонажа? Все текущие данные персонажа будут потеряны.',
    cancel: 'Отмена',
    page: 'Страница',
    saveToDb: 'Сохранить в Базу',
    loadFromDb: 'Загрузить из Базы',
  },
  characterInfo: {
    title: 'Информация о Персонаже',
    name: 'Имя Персонажа',
    race: 'Раса',
    rank: 'Ранг',
    experience: 'Очки Опыта',
  },
  attributes: {
    title: 'Атрибуты',
    Agility: 'Ловкость',
    Smarts: 'Смекалка',
    Spirit: 'Дух',
    Strength: 'Сила',
    Vigor: 'Выносливость',
    modifier: 'Модификатор',
  },
  skills: {
    title: 'Навыки',
    addSkill: 'Добавить Навык',
    importSkills: 'Импортировать Навыки',
    skillName: 'Название Навыка',
    skillSet: 'Набор Навыков',
    dieType: 'Тип Кости',
    modifier: 'Модификатор',
    linkedAttribute: 'Связанный Атрибут',
    defaultSkills: 'Стандартные Навыки',
    actions: 'Действия',
    sourcePage: 'Страница'
  },
  derivedStats: {
    title: 'Производные Характеристики',
    pace: 'Шаг',
    parry: 'Защита',
    toughness: 'Стойкость',
    charisma: 'Харизма',
  },
  combat: {
    title: 'Боевые Характеристики',
    wounds: 'Раны',
    fatigue: 'Усталость',
    bennies: 'Фишки',
  },
  edges: {
    title: 'Черты',
    addEdge: 'Добавить Черту',
    edgeName: 'Название Черты',
    description: 'Описание',
    addExisting: 'Добавить Существующую',
    selectEdge: 'Выбрать Черту'
  },
  hindrances: {
    title: 'Изъяны',
    addHindrance: 'Добавить Изъян',
    hindranceName: 'Название Изъяна',
    type: 'Тип',
    description: 'Описание',
    major: 'Большой',
    minor: 'Малый',
    addExisting: 'Добавить Существующий',
    selectHindrance: 'Выбрать Изъян',
  },
  gear: {
    title: 'Снаряжение',
    addGear: 'Добавить Снаряжение',
    itemName: 'Название Предмета',
    weight: 'Вес',
    notes: 'Заметки',
    actions: 'Действия'
  },
  weapons: {
    title: 'Оружие',
    addWeapon: 'Добавить Оружие',
    weaponName: 'Название Оружия',
    range: 'Дистанция',
    damage: 'Урон',
    ap: 'Пробивание',
    weight: 'Вес', 
    notes: 'Заметки',
    addExisting: 'Добавить Существующее',
    selectWeapon: 'Выбрать Оружие',
    actions: 'Действия',
    sourcePage: 'Страница'
  },
  powers: {
    title: 'Силы',
    addPower: 'Добавить Силу',
    powerName: 'Название Силы',
    powerPoints: 'Очки Силы',
    range: 'Дистанция',
    duration: 'Длительность',
    effect: 'Эффект',
    addExisting: 'Добавить Существующую',
    selectPower: 'Выбрать Силу',
    sourcePage: 'Страница'
  },
}; 